### ISSUE TITLE
Run with QEMU?

### ISSUE THREAD

**Issue by JonasVautherin** [e-ale/meta-pocketbeagle#3]
I am quite new to Yocto, and I was trying to run my pocketbeagle image with QEMU. However, `runqemu pocketbeagle` tries to find `*.qemuboot.conf`:

```
build/tmp/deploy/images/pocketbeagle/*.qemuboot.conf': No such file or directory
```

Is there an obvious reason why it couldn't run with qemu? Or should I try to write the `qemuboot.conf` file myself?

**Comment by behanw** [comment]
If you build it for PocketBeagle, you can’t run it in QEMU. If you want to run it in QEMU you’d have to chose your machine type as qemuarm. They are different platforms after all.

The peripherals for the PocketBeagle HW and the synthetic HW in QEMU are different.

I hope this helps,

Behan

**Comment by JonasVautherin** [comment]
Yes that's helpful. 

Not completely clear to me though. I remember having run a Raspbian image in QEMU using some kind of custom kernel for QEMU. Is that exactly the difference coming from setting the machine type in Yocto?

**Comment by behanw** [comment]
LOL. Don’t ever assume what’s done on the raspberry-pi is normal. What you’re describing is very much a hack and not how it was intended.

Just because it can be done doesn’t mean it should be. The right way is changing the MACHINE to qemuarm.

Behan

**Comment by JonasVautherin** [comment]
Got it. Thanks a lot for the insights!
