### ISSUE TITLE
Query regarding image launch and minimal bundle image 

### ISSUE THREAD

**Issue by JohnGoogl** [e-ale/meta-pocketbeagle#7]
Hello Everyone,

Firstly, thanks for all your contributions to the yocto community.

With mention updates able to build Ok:

- MACHINE ??= "pocketbeagle"
- IMAGE_FSTYPES += "cpio.xz"

But, somehow build failing with **INITRAMFS_IMAGE_BUNDLE** (as shared below).

- INITRAMFS_IMAGE = "core-image-minimal-initramfs"
- INITRAMFS_IMAGE_BUNDLE = "1"
- VIRTUAL-RUNTIME_dev_manager = "busybox-mdev"

**Build error:**
$ bitbake core-image-minimal
Loading cache: 100% |                                                                                                                                                                      | ETA:  --:--:--
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |#####################################################################################################################################################################| Time: 0:00:27
Parsing of 913 .bb files complete (0 cached, 913 parsed). 1846 targets, 67 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'initramfs-module-install' (but /home/build/poky/meta/recipes-core/images/core-image-minimal-initramfs.bb RDEPENDS on or otherwise requires it)
initramfs-module-install was skipped: incompatible with host arm-poky-linux-gnueabi (not in COMPATIBLE_HOST)
NOTE: Runtime target 'initramfs-module-install' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['initramfs-module-install']
ERROR: Required build target 'core-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-minimal', 'virtual/kernel', 'core-image-minimal-initramfs', 'initramfs-module-install']

Summary: There were 2 ERROR messages, returning a non-zero exit code.
$

Actually, am not sure either this scenario validity as am new to Yocto.. any thoughts on this would be appreciated pls.

Also, would like to have the documentation/links which helps for testing the build as well any possibility of reducing the image size for lowest possible.

Thanks in advace!

Best Regards.
John

**Comment by twoerner** [comment]
This is not a meta-pocketbeagle-specific issue. I haven't used an initramfs in decades. Please check with the yocto/oe community directly.
