### ISSUE TITLE
Unable to access pocketbeagle 

### ISSUE THREAD

**Issue by lokesh-chitla** [e-ale/meta-pocketbeagle#8]
Hi, Am new to pocketbeagle staff, and facing issue in accessing device via ssh/minicom from Ubuntu host, please let me know your inputs.

Steps for reference shared below:
1) Able to build pocketbeagle image with adding https://github.com/e-ale/meta-pocketbeagle.git layer fallowed by mention updates:
- MACHINE ??= "pocketbeagle"
- PREFERRED_VERSION_linux-yocto ?= "6.1%"

2) Using balenaEthcher could install Image (core-image-minimal-pocketbeagle.rootfs..wic).
3) While loading image can see leds blinking as expected, so per my understanding system looks up.
4) But, to check same like OS or system-up am not unable to access/login to hardware with ssh/minicom, no new Ip address listed in my host and unable to ping the hardware.

Would appreciate any inputs on same related to accessing device from Ubuntu (host) or any documentation pls..

Just for reference, with pocketbeagle portal Image(am335x-debian-11.7-iot-armhf-2023-09-02-4gb.img.xz) login working via ssh /192.168.6.2

Thanks in advance!

Best Regards,
Lokesh

**Comment by twoerner** [comment]
Configuring networking on a yocto-built image is not a meta-pocketbeagle-specific issue, it is related to which init system you are using. Please check with the documentation of your init system and the yocto community in general to determine how to configure networking in any yocto-built image.
